
vae:
  input_dim: 2000 # should be the same as the number of the highly variable genes
  latent_dim: 128
  n_hidden: 1024
  n_layers: 1
  dropout_rate: 0.1
  is_vae: true
  recon_loss: "mse" # "mse" | "bce"
  out_activation: "identity"  # use "sigmoid" if recon_loss="bce"
  beta_kl: 1.0  # beta-VAE


dataset:


train:

