
vae:
  input_dim: 2000
  latent_dim: 128
  n_hidden: 1024
  n_layers: 2
  dropout_rate: 0.1
  is_vae: false
  recon_loss: "mse" # "mse" | "bce"
  out_activation: "identity"  # use "sigmoid" if recon_loss="bce"
  beta_kl: 1.0  # beta-VAE

dataset:
  data_path: "../data/Tosches_turtle_processed.h5ad"

train:
  model_class: "VAE"  # "VAE" | "ZINBVAE"
  batch_size: 64
  learning_rate: 1e-3
  num_epochs: 100
  log_interval: 10
  save_interval: 10
  device: "cuda"  # "cuda" | "cpu"
  seed: 42
  